-- CREAR BASE DE DATOS
CREATE DATABASE PROYECTOS;
USE PROYECTOS;

-- CREAR TABLA CON LAS COLUMNAS Y RESTRICCIONES
CREATE TABLE DEPARTAMENTO
(ID_DPTO INT AUTO_INCREMENT NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
PRESUPUESTO DEC(15,2) NULL,

PRIMARY KEY(ID_DPTO),
CHECK (PRESUPUESTO >= 5000)
);
CREATE INDEX NOMBRE_INDICE ON DEPARTAMENTO(NOMBRE); -- CREAR INDICE

-- CREAR TABLA CON LAS COLUMNAS Y RESTRICCIONES
CREATE TABLE PROYECTOS
(ID_PROY INT AUTO_INCREMENT NOT NULL,											
NOMBRE VARCHAR(50) DEFAULT'INDEF' UNIQUE,
FECHA_INI DATE NOT NULL,
FECHA_FIN DATE NOT NULL,

PRIMARY KEY(ID_PROY)
);

-- CREAR TABLA CON LAS COLUMNAS Y RESTRICCIONES
CREATE TABLE EMPLEADOS
(ID_EMP INT AUTO_INCREMENT NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
SEXO ENUM('M','F') NOT NULL,
FECHA_NAC DATE NOT NULL,
MUNICIPIO VARCHAR(50) NOT NULL,
SUELDO DEC(7,2) NOT NULL,

ID_DPTO INT NULL,			-- NULO
PRIMARY KEY(ID_EMP),
FOREIGN KEY(ID_DPTO)REFERENCES DEPARTAMENTO(ID_DPTO) 	-- SIN COMA 
ON DELETE SET NULL,			-- PUEDES BORRAR UN DEPARTAMENTO Y PONE A NULL LAS CLAVES AJENAS DE LOS EMPLEADOS QUE HACIAN REFERENCIA A ESE DEPARTAMENTO BORRADO
CHECK(SUELDO >= 1000)
);

-- CREAR TABLA CON LAS COLUMNAS Y RESTRICCIONES
CREATE TABLE RENACIDA
(ID_PROY INT NOT NULL,
ID_EMP INT NOT NULL,

PRIMARY KEY(ID_PROY, ID_EMP),
FOREIGN KEY(ID_PROY)REFERENCES PROYECTOS(ID_PROY),
FOREIGN KEY(ID_EMP)REFERENCES EMPLEADOS(ID_EMP)
);

-- INSERTAMOS DATOS DE DEPARTAMENTOS
INSERT INTO DEPARTAMENTO
VALUES(1,'I+D',50000);

INSERT INTO DEPARTAMENTO
VALUES(2,'DISEÑO',25000);

INSERT INTO DEPARTAMENTO
VALUES(3,'VENTAS',15000);

INSERT INTO DEPARTAMENTO
VALUES(4,'MARKETING',10000);

INSERT INTO DEPARTAMENTO
(ID_DPTO,NOMBRE)
VALUES(5,'PROGRAMACIÓN');


-- INSERTAMOS DATOS DE EMPLEADOS
INSERT INTO EMPLEADOS
VALUES(10478,'ALBERTO','PEREZ LOPEZ','M','1969-10-12','MADRID',1500,1);

INSERT INTO EMPLEADOS
VALUES(10479,'GLORIA','RUIZ RUIZ','F','1965-11-07','SEVILLA',1650,2);

INSERT INTO EMPLEADOS
VALUES(10480,'ANTONIO','GARCIA MONTERO','M','1960-10-07','MADRID',1350,1);

INSERT INTO EMPLEADOS
VALUES(10481,'ANA','LOPEZ RAMIREZ','F','1990-10-01','SEVILLA',1250,3);

INSERT INTO EMPLEADOS
VALUES(10482,'EDUARDO','CHICON TERRALES','M','1980-11-07','CORDOBA',1470,2);


-- INSERTAMOS DATOS DE PROYECTOS
INSERT INTO PROYECTOS
VALUES(1,'SINUBE','2018-01-01','2018-03-15');

INSERT INTO PROYECTOS
VALUES(2,'TRASPI','2018-02-15','2018-12-30');

INSERT INTO PROYECTOS
VALUES(3,'RUNTA','2018-06-06','2018-09-15');

INSERT INTO PROYECTOS
VALUES(4,'CARTAL','2018-05-05','2018-09-25');


-- INSERTAMOS DATOS DE RENACIDA
INSERT INTO RENACIDA
VALUES(1,10478);

INSERT INTO RENACIDA
VALUES(3,10480);

INSERT INTO RENACIDA
VALUES(1,10481);

INSERT INTO RENACIDA
VALUES(2,10482);


/*-- MODIFICACIONES

-- MODIFICAMOS EL SUELDO A UN EMPLEADO
UPDATE EMPLEADOS
SET SUELDO= 1888
WHERE ID_EMP= 10478;

-- MODIFICAMOS EL NOMBRE DEL DEPARTAMENTO 5
UPDATE DEPARTAMENTO
SET NOMBRE= 'CIBERSEGURIDAD'
WHERE ID_DPTO= 5;

-- MODIFICAMOS EL MUNICIPIO DE UN EMPLEADO
UPDATE EMPLEADOS
SET MUNICIPIO= 'LEÓN'
WHERE ID_EMP= 10482; 

-- CAMBIAMOS LA FECHA_FIN A UN PROYECTO
UPDATE PROYECTOS
SET FECHA_FIN= '2019-02-01'
WHERE ID_PROY= 4;


-- COMPROBANDO LAS RESTRICCIONES

-- ELIMINAMOS UN DEPARTAMENTO
DELETE FROM DEPARTAMENTO
WHERE ID_DPTO= 1;

-- PRESUPUESTO MAYOR O IGUAL A 5000
INSERT INTO DEPARTAMENTO
(NOMBRE,PRESUPUESTO)
VALUES('CIBERSEGURIDAD',5000);

-- PRESUPUESTO MENOS QUE 5000
INSERT INTO DEPARTAMENTO
(NOMBRE,PRESUPUESTO)
VALUES('SISTEMAS',4999);

-- VALOR POR DEFECTO EN EL CAMPO NOMBRE DE LA TABLA PROYECTOS
INSERT INTO PROYECTOS
(FECHA_INI,FECHA_FIN)
VALUES('2018-01-01','2018-03-15');

-- EL SUELDO DEL EMPLEADO NO PUEDE SER INFERIOR A 1000 EUROS
INSERT INTO EMPLEADOS
VALUES(10483,'EDU','GONZALEZ LOPEZ','M','1985-11-07','MADRID',1000,2);*/


